### ISSUE TITLE
[Task] Harvester v0.3.0 release checklist 

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1116]
**What's the task? Please describe.**
Action items for releasing v0.3.0 & RC releases

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] decide if we'd like to ship with a customized kernel for https://github.com/harvester/harvester/issues/1342 
- [x] bump the embedded rancher server to the latest `v2.6.1-harvester2` release.
- [x] upgrade the installer with newOS:
  - [x] verify new support bundle-kit.
  - [x] verify the harvester-network-controller is compatible with both RKE2 and newOS.
- [x] bump longhorn to the v1.2.2 latest release. https://github.com/harvester/harvester/pull/1383
- [x] verify multi-cluster and multi-tenant features by importing the Harvester cluster to the central rancher.
  - [x] using `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html` to replace the deafult `ui-dashboard-index` before this [PR](https://github.com/rancher/dashboard/pull/3726) is merged.
- [x] update the [README file](https://github.com/harvester/harvester/blob/master/README.md) of the harvester main repo
- [x] verify air-gap environment installation (release note to specify the supported scope).
- [x] verify harvester related repos:
  - [x] [harvester-network-controller](https://github.com/harvester/network-controller-harvester)
  - [x] [node-disk-manager](https://github.com/harvester/node-disk-manager)
  - [x] [harvester-cloud-provider](https://github.com/harvester/cloud-provider-harvester)
  - [x] [harvester-load-balancer](https://github.com/harvester/load-balancer-harvester)
  - [x] [harvester-upgrade-responder](https://github.com/harvester/upgrade-responder)
  - [x] [harvester-csi-driver](https://github.com/harvester/harvester-csi-driver)
  - [x] [docker-machine-driver](https://github.com/harvester/docker-machine-driver-harvester)
  - [x] [terraform-provider](https://github.com/harvester/terraform-provider-harvester)
  - [x] tag rancher/harvester-os:$tag -> dev-head https://github.com/harvester/os2
- [x] make sure the charts of [harvester/charts](https://github.com/harvester/charts) is bumped accordingly.
- [x] update harvester v0.3.0 related documentations https://github.com/harvester/harvester/issues/1347
- [x] switch v0.3.0-dev doc to v0.3.0 and make it the default page.
- [x] make sure the e2e test passes all the testing cases.
- [x] add v0.3.0 release note.

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/releases/tag/v0.3.0
