### ISSUE TITLE
[EPIC] Documentation for v0.3.0 

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1347]
## Feature
- [x] Update GitHub frontpage (https://github.com/harvester/harvester) https://github.com/harvester/harvester/pull/1408
     - [x] new UI screenshot
     - [x] Correct diagram (it still shows K3OS)
     - [x] Correct minimal requirement.     
- [x] Update documentation frontpage https://docs.harvesterhci.io/v0.3/
     - [x] new UI screenshot
     - [x] Correct diagram (it still shows K3OS)
     - [x] Correct minimal requirement.
- [x] Update Harvester frontpage video from Victor
- [x] PXE configuration reference (including all the options, e.g. bonded NIC for vlan) - @futuretea @bk201 
- [x] Network configuration - @yaocw2020 
- [x] Baremetal VIP - @yaocw2020 
- [x] Rancher integration 0 @guangbochen & @gitlawr **(Including spin up Rancher server inside the Harvester)**
  - [x] Virtualization Management - @WuJun2016 
      - [x] Authentication
      - [x] Multi-tenancy
      - [x] How to Delete imported cluster
  - [x] Node driver - @n313893254  
      - [x] RKE1 with imported Harvester cluster
          - [x] Cloud Provider support (Load Balancer)
          - [x] CSI driver support
      - [x] RKE2 with imported Harvester cluster
          - [x] Cloud Provider support (Load Balancer)
          - [x] CSI driver support
      - [x] RKE1 with external Harvester cluster
      - [x] RKE2 with external Harvester cluster
- [x] Hot plug - @guangbochen @weihanglo 
- [x] Bonded NIC setup - @yaocw2020 
- [x] Terraform - @futuretea 
- [x] Multidisk management - @guangbochen @weihanglo 
- [x]  Troubleshooting (e.g. Kernel debug, RW partition etc) - @gitlawr @bk201 

## Release note
- [x] Upgrade is not supported (Change to automatic upgrade is not support if we can figure a manual upgrade path)
- [x] Backup data deletion doesn't take effect: https://github.com/harvester/harvester/issues/1333
- [x] VM's function won't work when host is down https://github.com/harvester/harvester/issues/1360 / https://github.com/harvester/harvester/issues/1361
- [x] UI discrepancy between standalone interface vs Rancher integrated interface

Additional release notes: https://github.com/harvester/harvester/issues?q=is%3Aopen+is%3Aissue+label%3Arequire%2Frelease-note

Release note will be available and updated at https://github.com/harvester/release-notes/blob/main/v0.3.0.md

**Comment by yasker** [comment]
Assign to @guangbochen temporarily to assign the task out.

**Comment by guangbochen** [comment]
close in favor of https://docs.harvesterhci.io/
