### ISSUE TITLE
[Task] Harvester v1.0.0 release checklist 

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1626]
**What's the task? Please describe.**
Action items for releasing v0.3.0 & RC releases

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] Support manual version upgrade to v1.0.0 #1665. (experimental)
- [x] Support automatic upgrade from v1.0.0 to later versions. #1022 [moved to 1.0.1]
- [x] Verify Rancher MCM feature with Rancher v2.6.3.
- [x] Verify air-gap environment installation (release note to specify the supported scope).
  - [x] #1052
- [x] Bump the support-bundle-kit version https://github.com/harvester/harvester/pull/1698
- [x] Update the [README file](https://github.com/harvester/harvester/blob/master/README.md) of the harvester v1.0.0 release
- [x] Bump dependency charts:
  - [x] [harvester-network-controller](https://github.com/harvester/network-controller-harvester)
  - [x] [node-disk-manager](https://github.com/harvester/node-disk-manager)
  - [x] [harvester-upgrade-responder](https://github.com/harvester/upgrade-responder) (optional)
  - [x] kubevirt v0.45.0
  - [x] Longhorn to v1.2.3
- [x] update harvester v1.0.0 related docs https://github.com/harvester/docs/tree/v1.0 and make it as the default version
  - [x] Update documentation for RKE1 and RKE2 integration with the new UI.
- [x] cut terrraform v1.0.0 related release https://github.com/harvester/terraform-provider-harvester/pull/21
- [x] make sure the e2e test passes all the testing cases.
- [x] add v1.0.0 release note.
- [x] Update POC guide for v1.0.0

**Comment by guangbochen** [comment]
close in favor of the v1.0.0 release and the upgrade doc will be tracked by https://github.com/harvester/harvester/issues/1665 separately.
