### ISSUE TITLE
[FEATURE] Rebase Harvester on SLE Micro for Rancher

### ISSUE THREAD

**Issue by wjimenez5271** [harvester/harvester#1933]
This feature request is to rebase Harvester's OS platform on the new operating system SLE Micro for Rancher.

# Dev updates
## Tasks
- [x] **Clarify how to install packages using `zypper` with SLE Micro for Rancher team**
    - If we want to install from SLE Micro repository, seems like the only way is via OBS (Open Build System). Is it possible to pull the image and install packages using a `Dockerfile`?
    - Some packages required by the original Harvester OS image are already installed on SLE Micro for Rancher image. I've written a [script](https://gist.github.com/johnliu55tw/1c124960593b81526dd8e472db347f8b) to test what is missing, and those listed [here](https://build.opensuse.org/package/view_file/home:jliu/Test/Dockerfile?expand=1) should be it.
    - What about those packages that are missing SLE Micro repository? (`nano` and `rng-tools`)

- [x] **Double-check the unnecessary luet packages**
    - Already done some [cleanup](https://github.com/johnliu55tw/os2/commit/2083c3cd9d54a6e3dd4860bf66921c4bf5882328#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L112-L123). Still worth checking with SLE Micro for Rancher team to see if some of them will be covered by the image.

- [x] **Fix GRUB rebranding issues**
    - After installation, GRUB menu does not get rebranded. Still shows `Rancher OS` 
    - SLE Micro for Rancher contains a cOS config `/etc/cos/config` which has [higher precedence](https://rancher-sandbox.github.io/cOS-toolkit/docs/customizing/general_configuration/) than our cOS config `/etc/os-release`.
    - Solution: [Remove `/etc/cos/config`](https://github.com/johnliu55tw/os2/commit/2083c3cd9d54a6e3dd4860bf66921c4bf5882328#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R34-R35) while building the Harvester OS image. Most of the settings inside are default values anyway.

- [x] **Specify Rancher's version installed by Rancherd**
    - New way: https://github.com/harvester/harvester-installer/pull/146
    - The current way still works. as Rancher's version is still pinned to the one we needed.

- [x] **Replace `bootstrapResources` with `resources`**
    - `bootstrapResources` is [deprecated by Rancherd](https://github.com/rancher/rancherd/issues/23). We need to replace them with `resources`.
    - This will **not** affect the upgrade path since `bootstrapResources/resources` are only for bootstrapping Rancher. Once the Harvester clusters are created, they are not used afterward.
    - If this also works in the older version of Rancherd we can merge this change before we even updated the Harvester OS.

**Comment by yasker** [comment]
Tentatively scheduled for v1.0.2.

**Comment by simonflood** [comment]
Can I ask why SLE Micro and not openSUSE MicroOS? The former requires registering to get updates whereas the latter does not. Or perhaps you're planning on disabling transactional updates?

**Comment by yasker** [comment]
@simonflood SLE Micro for Rancher will be an additional delivery method of SLE Micro (OCI image), that will be freely available without the requirement for a subscription or registration.

Rest assured. We won't require users to register to get updates. There should be no difference in the user experience.

(Reworded to clarify)

**Comment by simonflood** [comment]
Thanks. Perhaps you meant to write "SLE Micro for Rancher is different from openSUSE MicroOS"? SLE Micro for Rancher sounds a lot like SLE Micro which "is an ultra-reliable, lightweight operating system purpose built for containerized and virtualized workloads. It leverages the enterprise hardened security and compliance components of SUSE Linux Enterprise and merges them with a modern, immutable, developer-friendly OS platform." (from https://www.suse.com/products/micro/ )

If SLE Micro for Rancher is not the same as SLE Micro then I suggest renaming it to avoid confusion. I'll await further details before commenting further.

**Comment by yasker** [comment]
@simonflood Sorry for the confusion. I've reworded my comment. SLEMicro for Rancher is SLEMicro in a different delivery method, that will be freely available to Harvester users.

**Comment by bk201** [comment]
We also need to check if the interface name rule change also happens in the new OS: https://github.com/harvester/harvester/issues/2073

**Comment by bk201** [comment]
Add `require/release-note` label. We'll share with community about the rebase.

**Comment by tjjh89017** [comment]
https://github.com/harvester/harvester-installer/pull/296

**Comment by TachunLin** [comment]
#### Test plan
1. Check can download support bundle correctly, check no empty file
2. Check debug command exists (include necessary packages)
3. Check the daily E2E test result
5. Can upgrade 3 nodes harvester correctly
6. Version check
  $ cat /etc/os-release
7. Major feature smoke test
  - Images
  - Volumes
  - Virtual Machine
  - Live Migration 
  - Backup 
  - Rancher integration

**Comment by TachunLin** [comment]
### Test Result
 
- [x] **PASS** Check can download support bundle correctly, check can access every file without empty

- [x] **PASS** Check debug command exists (include necessary packages)
  - k9s
  - kubectl
  - ip
  - lsblk, gisk
  - tar, gzip
  - ctr
  - zstd

- [x] **PASS** : Daily E2E test on Jenkins server 

-  **SKIP** Upgrade test cancel since currently not yet able to upgrade from 1.0.2 to 1.0.3 master  

- [x] **PASS** : Version check
  - SLE Micro: 5.2
  - VARIANT_ID: Harvester-20220705

  ```
  harvester-gv2ks:~ # cat /etc/os-release
  NAME="SLE Micro"
  VERSION="5.2"
  VERSION_ID="5.2"
  PRETTY_NAME="Harvester master"
  ID="sle-micro-rancher"
  ID_LIKE="suse"
  ANSI_COLOR="0;32"
  CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.2"
  VARIANT="Harvester"
  VARIANT_ID="Harvester-20220705"
  GRUB_ENTRY_NAME="Harvester master"
  ```

- [x] **PASS** Major feature smoke test
  - [x] Images
    - [x] Auto setup image from cypress environment
    - [x] Create an image with valid image URL
    - [x] Create image with invalid URL
    - [x] Delete VM with exported image
    - [x] Create a ISO image via upload
  - [x] Volume
    - [x] Create volume from NEW and VM image
    - [x] Delete volume that is not attached to a VM
    - [x] Add volume to virtual machine
    - [x] Detach volume from virtual machine
  - [x] Networks
    - [x] Create/delete network
    - [x] Check network with DHCP
    - [x] Check network with Manual Mode
  - [x] Virtual Machine
    - [x] Create a new VM and add Enable USB tablet option
    - [x] Create a new VM and add Install guest agent option
    - [x] Verify Booting in EFI mode checkbox
    - [x] Create a vm with all the default values
    - [x] Create VM without memory provided
    - [x] automatic assignment to different nodes when creating multiple vm's
  - [x] Live migration
    - [x] Migrate a VM that has multiple volumes
    - [x] Migrate a VM created with user data config
  - [x] Backup
    - [x] Backup VM to S3 target
  -  [x] Rancher integration (master-8f01b558-head, rancher v2.6.5)
      - [x] Provision RKE1 cluster
      - [x] Delete RKE1 cluster
      - [x] Provision RKE2 cluster
      - [x] Delete RKE2 cluster
      - [x] Provision K3s cluster
      - [x] Create Havester cloud provider
      - [x] Create Harvester CSI driver

**Comment by TachunLin** [comment]
Verified **fixed** on master-0f590757-head. Close this issue.

### Result
According to the previous test result https://github.com/harvester/harvester/issues/1933#issuecomment-1182832981
We have passed all test plan scenarios. 

### Test Information
* Test Environment: 4 nodes harvester on dolphin bare machine
* Harvester version: master-0f590757-head

### Verify Steps
1. Download support bundle in support page 
2. Extract support bundle and check every file content
3. Vagrant install master release
4. Execute backend E2E regression test 
5. Run frontend Cypress automated test against feature Images, Networks, Virtual machines
6. Run manual test against feature Volume, Live migration and Backup and rancher integration
