### ISSUE TITLE
[EPIC] Harvester cloud provider enhancement

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#2134]
The epic issue is the collection of the issue related to the Harvester cloud provider enhancement.
- [x] https://github.com/harvester/harvester/issues/1676
- [x] https://github.com/harvester/harvester/issues/1458
- [x] https://github.com/harvester/harvester/issues/1762
- [x] https://github.com/harvester/harvester/issues/1580
- [x] https://github.com/harvester/harvester/issues/2354
- [x] Add migration support
- [x] https://github.com/harvester/harvester/issues/2753

Moved to v1.2.1:
- [ ] https://github.com/harvester/harvester/issues/1834

**Comment by guangbochen** [comment]
Close the epic issue as its sub-tasks are either close or verified.
For the other partially related issues, it will be tracked independently via:
- https://github.com/harvester/docs/pull/323
- https://github.com/harvester/harvester/issues/4329
- https://github.com/harvester/harvester/issues/4232
