### ISSUE TITLE
[EPIC] VLAN enhancement

### ISSUE THREAD

**Issue by tjjh89017** [harvester/harvester#2236]
### Description:

This epic issue is used to track down issues related to VLAN enhancements. The goal of VLAN enhancements is to support:

- Configuring VLAN on the management network.
- Supports multiple VLANs with independent NICs.
- VM scheduling and live migration with VLAN network topology-aware.

### Installation

- [x] Installer should only configure management interface in the future version. All other interface configurations will be handled by CR and Network Controller.
    - [x] https://github.com/harvester/harvester/issues/1390
    - [x] https://github.com/harvester/harvester/issues/1647
### Network Controller
- [x] https://github.com/harvester/harvester/issues/2259
- [x] https://github.com/harvester/harvester/issues/2828

### Harvester Enhancement Proposal(HEP)
- [x] https://github.com/harvester/harvester/pull/2161

### Upgrading
- [x] https://github.com/harvester/harvester/issues/2734

### Document
- [x] https://github.com/harvester/harvester/issues/2735

### Terraform
- [x] https://github.com/harvester/harvester/issues/2790

### UI enhancement
- [x] https://github.com/harvester/harvester/issues/2794
- [x] https://github.com/harvester/harvester/issues/2841

**Comment by WuJun2016** [comment]
Hi,  @tjjh89017  I'm looking at the HEP documentation and I see that there are UI-related changes required, if so, please help me add the `require/ui` label.    thanks

**Comment by tjjh89017** [comment]
@WuJun2016 It will depend on Canwu's enhancement.
Currently, we don't know which part will need UI.
Thanks a lot

**Comment by guangbochen** [comment]
close this epic issue since all feature-related items are merged or verified, the doc and HEP will be tracked by independent issues accordingly.
