### ISSUE TITLE
[FEATURE] vGPU Support

### ISSUE THREAD

**Issue by tlehman** [harvester/harvester#2764]
**Is your feature request related to a problem? Please describe.**
Customers with NVIDIA cards that support the [vGPU](https://www.nvidia.com/en-us/data-center/virtual-solutions/) feature currently can't use it with VMs created by Harvester. This is preventing them from using the acceleration features in their workflows, adding cost by making their work take longer.

**Describe the solution you'd like**
Adding support for NVIDIA vGPU to the host, including the drivers, configuration, and a UI to manage the configuration. Specifically, the UI should allow the user to enable virtual GPUs and then assign them to VMs. This is different from #992, since there can be multiple vGPUs for a single physical GPU. The multiple vGPUs can be flexibly shared so that multiple VMs use the same GPU. This is different from #992, which allows a single VM to control a single GPU, in a one-to-one manner. 

**Describe alternatives you've considered**
- #992 but it's not sufficient, because there are NVIDIA devices and workloads that can't possibly max out the device. The solution is to add support for this vGPU (in Kubernetes it's called a Mediated Device), and then multiple VMs can share the underlying hardware and make maximum use of it.

**Additional context**
vGPU is analogous to SR-IOV, in that they both involve drivers (that will be in the host) which expose virtual devices, with their own PCI Addresses. Those virtual PCI addresses can then be fully owned by VMs. The PCI passthrough work in #992 is necessary to begin working on this issue.

**Comment by torchiaf** [comment]
We will need additional information about context/area of the UI impacted by this new feature @bk201 .

**Comment by bk201** [comment]
Reopen. QA should verify the issue before closing it.

**Comment by noahgildersleeve** [comment]
# vGPU testing scenarios
For testing all testing was done on focal cloud images with cuda and a nVidia a102 GPU and nvidia driver `NVIDIA-Linux-x86_64-525.60.13`

- [x] Enable vGPU addon PASS
- [x] Select server side driver PASS
- [x] Try to add vGPU profiles to card that doesn't support vGPU PASS
- [x] Add vGPU devicePASS
- [x] Remove device PASS
- [x] Add two vGPUs to vm PASS #5289 
        RETEST: I tested this again with the ramFB fix. It works with the edit to the YAML. There is going to be a doc update to address this.
- [ ] ~~add one vGPU to VM that already has active vGPU FAIL #5289 EDIT: I'm going to mark this as kind of N/A since the workaround from the previous test~~
- [x] Try to add already used device UNSURE The functionality on this
- [x] Try to add too many devices in `advanced vGPU devices` PASS
- [ ] Try to remove vGPU that is in use FAIL #5293 (this is an issue with the UI that will be fixed in a UI PR

## Upgrade

- [ ] Add vGPU on server that has PCI passthrough addon enabled after upgrade from v1.2-head to v1.3.0

**Comment by noahgildersleeve** [comment]
validated in `master-a2c98e96-head`. Closing as validated. We need to test that upgrade scenario separately.
