### ISSUE TITLE
[EPIC] v1.1.0 upgrade issues

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2872]
The epic issue to summarize all upgrade issues:

## Investigating

- https://github.com/harvester/harvester/issues/2984 (as Known issue and move to v1.1.1)

## Merged

- [x] https://github.com/harvester/harvester/issues/2931 (minor)
- [x] https://github.com/harvester/harvester/issues/2907 (workaround)
- [x] https://github.com/harvester/harvester/issues/2920
- [x] https://github.com/harvester/harvester/issues/2892
- [x] https://github.com/harvester/harvester/issues/2867
- [x] https://github.com/harvester/harvester/issues/2865
- [x] https://github.com/harvester/harvester/issues/2833
- [x] https://github.com/harvester/harvester/issues/2893

## Others

- [ ] https://github.com/harvester/harvester/issues/2894 (happens in slow disk and there is a workaround, move to v1.1.1).

**Comment by bk201** [comment]
Close, we've fix issues in the description.
