### ISSUE TITLE
[Task] Harvester v1.1.0 release checklist

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3030]
**What's the task? Please describe.**
Action items for releasing v1.1.0 release

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] Update release note. https://github.com/harvester/release-notes/pull/18
- [x] Update upgrade-responder.
- [x] Support automatic upgrade from v1.0.3. https://github.com/harvester/docs/pull/217
- [x] Verify Rancher MCM feature with Rancher v2.6.9.
- [x] Verify air-gap environment installation (release note to specify the supported scope).
- [x] Update the [README file](https://github.com/harvester/harvester/blob/master/README.md) of the harvester v1.1.0 release
- [x] Bump dependencies:
  - [x] pci-devices (addon) 0.2.2
  - [x] vm-import (addon) 0.1.1
  - [x] node-manager 0.1.2
  - [x] [harvester-network-controller](https://github.com/harvester/network-controller-harvester) 0.3.0
  - [x] [node-disk-manager](https://github.com/harvester/node-disk-manager)  0.4.7
  - [x] whereabout: 0.1.1
  - [x] [harvester-node-manager](https://github.com/harvester/node-manager) 0.1.1
  - [x] Rancher v2.6.9
  - [x] RKE2 v1.24.7+rke2r1
  - [x] Kubevirt v0.54.0
  - [x] Longhorn to v1.3.2
  - [x] OS (updated in Oct 25)  
- [x] update harvester v1.1.0 related docs and make it as default version
- [x] cut terrraform v1.1.0 related release ([0.6.0](https://registry.terraform.io/providers/harvester/harvester/0.6.0) is published)
- [ ] ~~make sure the e2e test passes all the testing cases~~. Unable to test, we rely on QA regression tests.
- [ ] Update POC guide for v1.1.0 https://github.com/harvester/harvester/issues/2840

**Comment by bk201** [comment]
Close, The POC doc is tracked in https://github.com/harvester/harvester/issues/2840
