### ISSUE TITLE
[EPIC] Add further pre and post checks in harvester upgrade

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#3067]
**Describe the bug**
Just ran into an issue with the upgrade from 1.0.3 to 1.1.0 with two different cases:

1. there was a "orphaned" machine object in fleet-default
2. the upgrade from harvester 1.0.2 to 1.0.3 was completed but the cluster status "local" has been stuck in "Provisioning" 

**Expected behavior**
There should be additonal pre and post checks before and after any upgrade to verify the cluster is 100% ok before and 100% ok after the upgrade so that no left over actions / pending actions are there that might cause issues in the future.

**Environment**
 - Harvester ISO version: 1.0.2/1.0.3/1.1.0

**Additional context**

We should check 
- [ ] timesync status on all nodes (timedatectl)
- [x] the status of all volumes (health ok or detached)  (kubectl get volumes -A)
- [x] for sufficient free disk space (/, /usr/local, /var/lib/longhorn, /var/lib/harvester/defaultdisk and other longhorn disks)
- [x] node health / all nodes ready
- [x] kubectl get clusters.cluster.x-k8s.io local -n fleet-local
- [x] kubectl get machines -n fleet-local
- [ ] conflicting customizations in /oem/* (i.e. registries.yaml)
- [ ] sufficient memory and CPU in the nodes 
  - especially in case we add additional workload like monitoring/logging
  - For live-migration cases, we need to check if the rest nodes can absorb VMs from a upgrading node.

For some we should print a warning and block the upgrade and for some others we should allow the upgrade even with warning.

**Comment by Martin-Weiss** [comment]
Seems we have a "deprecated volumes check, already":
![grafik](https://user-images.githubusercontent.com/13362573/198676884-5f1d0a01-ebab-4de9-9948-dcbe40cdda9b.png)

But how to check this without the Longhorn UI available?

**Comment by starbops** [comment]
When LH UI is unavailable, the following command can be used to check the status of all the LH volumes:

```
$ kubectl -n longhorn-system get lhv
NAME                                       STATE      ROBUSTNESS   SCHEDULED   SIZE          NODE     AGE
pvc-8f9a780e-17dd-41bc-8cc8-a3f0a3e71636   attached   healthy      True        53687091200   node-3   7d12h
pvc-eab05ecb-6fb8-4f3c-a1f7-17d60fd30a25   attached   healthy      True        10485760      node-3   7d12h
```

**Comment by FrankYang0529** [comment]
https://github.com/harvester/harvester/pull/2836
- the status of all volumes (health ok or detached)  (kubectl get volumes -A)

https://github.com/harvester/harvester/pull/3093
- node health / all nodes ready
- kubectl get clusters.cluster.x-k8s.io local -n fleet-local
- kubectl get machines -n fleet-local

https://github.com/harvester/harvester/pull/3700
- for sufficient free disk space to load images (/usr/local)

TODO:
- timesync status on all nodes (timedatectl)
- conflicting customizations in /oem/* (i.e. registries.yaml)
- sufficient memory and CPU in the nodes (especially in case we add additional workload like monitoring/logging)

**Comment by bk201** [comment]
Related: https://github.com/harvester/harvester/issues/2935

**Comment by bk201** [comment]
Non-finished enhancements are tracked at https://github.com/harvester/harvester/issues/4926 and will continue there.
