### ISSUE TITLE
[FEATURE] Optimize for Frequent Power-off/Power-On operating procedures

### ISSUE THREAD

**Issue by rebeccazzzz** [harvester/harvester#3261]
**Context**
Running Harvester in edge or remote environments with either intermittent power or with devices needing to be turned off and moved to a new location frequently (sometimes daily). 

**Is your feature request related to a problem? Please describe.**
Operators turning the cluster off and on are not highly technical with Kubernetes and thus can't be expected to troubleshoot stuck containers that don't come back online after startup.

update 20230824:
This issue is converted into an **EPIC**, it touchs k8s, csi, VM, Linux and more, one HEP is required.

A Harvester cluster is deployed in the rough sequence of: 

`OS -> rancherd -> rke2 -> k8s ->  fleet -> harvester -> longhorn | monitoring | logging..., -> virtual-machine ...`

To shutodown the cluster safely, follow the roughly reverse sequence seems reasonable.

A bunch of sub-stories are created to work on them.

**Sub-stories in v1.3.0:**

**Bug fix and enhancement in v1.3.0:**

A couple of bugs with various phenomena, but the root cause is same: after a node reboots, kubelet fails to UnmountVolume
- [x] https://github.com/harvester/harvester/issues/4633 (validate after rke2 is bumped to v1.27.10; kubelet fail to UnmountVolume)
- [x] https://github.com/harvester/harvester/issues/4033
- [x] https://github.com/harvester/harvester/issues/3539
- [x] https://github.com/harvester/harvester/issues/4789
- [x]  https://github.com/harvester/docs/pull/519  (The issue #5109 was observed when validating 4633, may have no chance to be fixed in Harvester v1.3.0, add it to Harvester document, after document PR is merged, this issue #5109 will be moved to v1.4.0)

Others:
- [x] https://github.com/harvester/harvester/issues/4674
- [x] https://github.com/harvester/harvester/issues/3843 (possbible same root cause as 4674, will validate)
- [x] https://github.com/harvester/harvester/issues/4659

HEP PR:
- [x] https://github.com/harvester/harvester/pull/4464

Continuous enhancment in v1.4.0+:

EPIC: https://github.com/harvester/harvester/issues/5007 [ENHANCEMENT] Continuous enhancement on system robustness and resilience
- https://github.com/harvester/harvester/issues/4447
- https://github.com/harvester/harvester/issues/4450
- https://github.com/harvester/harvester/issues/4449
- https://github.com/harvester/harvester/issues/4451
- https://github.com/harvester/harvester/issues/4452
- https://github.com/harvester/harvester/issues/4448

Those ISSUEs/PRs could be checked & algined as well:
https://github.com/harvester/harvester/issues/3902
https://github.com/harvester/harvester/issues/3263
https://github.com/harvester/node-manager/pull/15

**Comment by w13915984028** [comment]
New updated scenario:

> Run 5+ VMs on the cluster (1~3 Nodes), stop all nodes at same time, then restart the cluster at certain time. Some VMs may stuck / take quite a long time to restart:

* Some may be related issues: 
#4033 
#3539
#3378 
#4633 
#4828 
https://github.com/harvester/harvester/issues/994#issuecomment-1144539305

**Comment by w13915984028** [comment]
The planned optimization and bug fix in v1.3.0 have been done, and the continuous enhancement is tracked new epic #5007 in Harvester v1.4.0. Close this issue now.
