### ISSUE TITLE
[ENHANCEMENT] Add tests for interactive installation

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3585]
**Is your enhancement related to a problem? Please describe.**

Our installer provisioning test can't catch failure in the interactive mode like this: https://github.com/harvester/harvester/issues/3584

**Describe the solution you'd like**

We need to test the interactive mode when a user submits a PR.
e.g. leverage openQA.

**Describe alternatives you've considered**

**Additional context**

**Comment by markhillgit** [comment]
@TachunLin do you have a status update about this?

**Comment by TachunLin** [comment]
I would like to add the scope and plan for testing the Harvester interactive mode.   

###  What's the test to develop? 
Utilize the [openQA](http://open.qa/) framework in SUSE to create automation test for [Harvester ISO installation](https://docs.harvesterhci.io/v1.3/install/index)

### Test Scope 
1. Cover the most basic ISO installation scenarios including
    - Create mode installation flow 
    - Join mode installation flow 
    - Binary mode installation flow (create and join) 
    - Legacy and MBR bios installation for CPU

2. Cover more ISO installation scenarios like
    - Disk type and size  
    - Network type 
    - Configuration 


### Describe the development stage and items

#### Stage 1 Test environment (Done) 
We already have ECM lab machine hp-156 hosting the openQA test environment. 
There we have openQA dashboard and test script running 

#### Stage 2 Develop basic ISO installation scenarios

- [x]  Create mode install
- [x]  Binary mode installation (create)
- [ ]  Join mode install
- [x]  Legacy bios install
- [x]  MBR bios install 


#### Stage 3 Build up Jenkins server and pipeline

- [ ] Build up Jenkins server on `hp-156`
- [ ] Create Jenkins pipeline to continuously running openQA tests


#### Stage 4 Build up Jenkins server and pipeline
- [ ] Integrate with Harvester installer CI when a user submits a PR

**Comment by TachunLin** [comment]
@markhillgit 
According to above development plan in , I would also like to update the current status of testing interactive installation.  

We already have openQA build up on `hp-156`.  There we have some test jobs running upon it including:
We can access the dashboard on http://172.19.106.112/ (requires vpn and portfowarding)

- Create mode install
- Binary mode installation (create)
- Legacy bios install
- MBR bios install

These tests are developed against Harvester `v1.2.1`, which need to be updated for the latest v1.3.0
![image](https://github.com/harvester/harvester/assets/29251855/e1b929df-71da-4f09-8730-3d5dd807db9a)

Next step would be figure out how to setup openswitch to make the **join mode installation** can work on openQA environment

**Comment by khushboo-rancher** [comment]
@bk201 I don't think @TachunLin or other QA team member has bandwidth to do this in 1.4.0.
