### ISSUE TITLE
[FEATURE] Harvester network-controller enhancement

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#369]
**Is your feature request related to a problem? Please describe.**

1. add tech docs to [rancher/harvester-network-controller](https://github.com/rancher/harvester-network-controller)
1. refactoring the harvester-network-controller
    * using CRDs
    * store and reconcile networks status using conditions
    * add per node configuration
1. new feature & enhancement
    - [x] support static IP address #367
    - [x]  get a list of physical NIC #362
    - [x]  set custom Physical NIC on each node #249
1. Add unit-test and review e2e testing cases
1. UI/UX design updates

**Comment by guangbochen** [comment]
@yaocw2020 u will need to update the `harvester-network-controller` chart in the harvester https://github.com/rancher/harvester/tree/master/deploy/charts/harvester/dependency_charts/harvester-network-controller.

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester-network-controller/pull/22

**Comment by TangStone** [comment]
### support static IP address #367 
**Validation Version**
- master-8d070c0e-head

- [x] 1.  Use the tab key to bring up Method for ipv4   
![image](https://user-images.githubusercontent.com/15829074/112262102-09199d00-8ca8-11eb-81f1-fc045a410f58.png)

2. Configure static IP address
- [x] 2.1 Legitimate static ip address settings
![image](https://user-images.githubusercontent.com/15829074/112263859-ee94f300-8caa-11eb-9714-cf1dec2a5f04.png)
![image](https://user-images.githubusercontent.com/15829074/112265162-fa81b480-8cac-11eb-9f73-65fc15a3ef15.png)
- [x] 2.2 Set up static network to add node to harvester

 - [x] 2.3 ip address legitimacy check
![image](https://user-images.githubusercontent.com/15829074/112261096-1fbef480-8ca6-11eb-9d47-07d72978b016.png)
![image](https://user-images.githubusercontent.com/15829074/112279087-7801f080-8cbe-11eb-93d2-3806cae541cd.png)

**Comment by TangStone** [comment]
### get a list of physical NIC #362
**Validation Version**
- master-8d070c0e-head
- [x] 1. Disable Vlan , Unable to view the list of physical NIC

![image](https://user-images.githubusercontent.com/15829074/112281513-1727e780-8cc1-11eb-8bfe-3b6ae3a33d11.png)
- [x] 2. Enable Vlan , able to view the list of physical NIC
![image](https://user-images.githubusercontent.com/15829074/112286058-e39b8c00-8cc5-11eb-83d2-f63a77e8dc2d.png)
- [x] 3. Set the default physical NIC for vlan in setting, and Network in Hosts automatically configures the default physical NIC
- [x] 4. Add suggestion that prefer to use physical NIC that has not been use by management network
![image](https://user-images.githubusercontent.com/15829074/112287661-902a3d80-8cc7-11eb-9d36-6bc0a2c7b232.png)
![image](https://user-images.githubusercontent.com/15829074/112288098-fa42e280-8cc7-11eb-9a9d-8902598deb88.png)
![image](https://user-images.githubusercontent.com/15829074/112288189-0f1f7600-8cc8-11eb-83c8-4f1e5b72a934.png)

**Comment by TangStone** [comment]
### set custom Physical NIC on each node #249
**Validation Version**
- master-8d070c0e-head

**The information of the deployed harvester node is as follows**
![image](https://user-images.githubusercontent.com/15829074/112314254-c5dd1f80-8ce3-11eb-8811-b0b12c564aa1.png)
**Step**
1. Click on the harvester2 node ellipsis and select "Edit Config" to enter the Network settings
![image](https://user-images.githubusercontent.com/15829074/112314927-8bc04d80-8ce4-11eb-8985-0112b253c0d0.png)
2. Login to the harvester node and view the physical NIC information
![image](https://user-images.githubusercontent.com/15829074/112315532-320c5300-8ce5-11eb-8466-8170785e81aa.png)
3. Click Physical NIC to view the physical NIC name in the list, and select eth2
![image](https://user-images.githubusercontent.com/15829074/112316473-19506d00-8ce6-11eb-887c-4042d18e9680.png)

**Results.**
1. the number and name of physical NICs of nodes obtained by harvester are correct
2. The single node NIC is set up successfully
![image](https://user-images.githubusercontent.com/15829074/112316188-d4c4d180-8ce5-11eb-9149-50c5c90bdba5.png)
![image](https://user-images.githubusercontent.com/15829074/112415242-7982f580-8d5e-11eb-810e-c05672957c7a.png)
