### ISSUE TITLE
[Task] Harvester v1.2.0-rc4 release

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#4215]
## Harvester v1.2.0-rc4 Release Tracking List:
View all the `v1.2.0-rc4` required issues via the [zenhub link](https://github.com/harvester/harvester/pulls#workspaces/harvester-602342943974310018a96c13/board?labels=required-for-rc%2Fv1.2.0&releases=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvODEzODQ).

### ⚠️ P0:
- [x] https://github.com/harvester/harvester/issues/3747 - owner @guangbochen @bk201 
   - [x] bump Longhorn to v1.4.3 https://github.com/harvester/harvester/pull/4242 @futuretea 
   - [x] bump OS base version https://github.com/harvester/harvester-installer/pull/543 @Vicente-Cheng 
- [x] https://github.com/harvester/harvester/issues/4210 - owner @Vicente-Cheng 
- [x] https://github.com/harvester/harvester/issues/2679 - owner @guangbochen @ibrokethecloud 
   - [ ] update [HEP](https://github.com/harvester/harvester/pull/3673) to reflect the new rancher vcluster design @guangbochen 
   - [x] add related doc and testing plans @ibrokethecloud 
   - [x] https://github.com/harvester/harvester/pull/4250
- [x] https://github.com/harvester/harvester/issues/3943 - owner @futuretea 
   - https://github.com/harvester/harvester/pull/4242

### ℹ️  P1:
 - [x] https://github.com/harvester/harvester/issues/4133 - owner @masteryyh 
   - https://github.com/harvester/harvester-installer/pull/528
 - [x] https://github.com/harvester/harvester/issues/4019 - owner @Vicente-Cheng 
 - [x] https://github.com/harvester/harvester/issues/2670 - owner @bk201 
   - https://github.com/harvester/harvester/pull/4223
   - https://github.com/harvester/harvester-installer/pull/496 
 - [x] https://github.com/harvester/harvester/issues/4027 - owner @WebberHuang1118 
 - [x] https://github.com/harvester/harvester/issues/4208
   - https://github.com/harvester/harvester/pull/4209
 - [x] addon enhancement - owner @ibrokethecloud 
   - https://github.com/harvester/harvester/issues/4108
   - https://github.com/harvester/harvester/issues/4109
   - https://github.com/harvester/harvester/pull/4227 - PR review @guangbochen @bk201 @chrisho 

### HEPs 
- [ ] https://github.com/harvester/harvester/pull/2378 - @ibrokethecloud address the review comment
- [x] https://github.com/harvester/harvester/pull/3666 - PR review @guangbochen @bk201 @LucasSaintarbor 
- [x] https://github.com/harvester/harvester/pull/3230 - @ibrokethecloud double check if this is needed or replace with a new one.

### TBD:
- https://github.com/harvester/harvester/issues/4156 - owner @connorkuehl 
- https://github.com/harvester/harvester/issues/4211 - owner @guangbochen

**Comment by guangbochen** [comment]
close as `v1.2.0-rc4` is complete and official release will be tracked via https://github.com/harvester/harvester/issues/4294
