### ISSUE TITLE
[TASK] Release Harvester v1.2.0

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#4294]
**What's the task? Please describe.**
Action items for releasing v1.2.0 release

**Describe the items of the task (DoD, definition of done) you'd like.**
- Pre-Release
  - [x] Pass regression test plan @khushboo-rancher 
    - [x] Verify Harvester MCM feature with Rancher `v2.7.6`
    - [x] Verify air-gap environment installation/upgrade.
        <img width="1758" alt="image" src="https://github.com/harvester/harvester/assets/4569037/bacff9e5-d6e5-46fb-9091-4e57ddd39adf">
  - [x] Harvester v1.2.0 doc @nunix https://github.com/harvester/docs/issues/373
  - [x] CVE scanning of OS and container images before pre-GA release @guangbochen 
  - [x] Update the [README file](https://github.com/harvester/harvester/blob/master/README.md) of the harvester v1.2.0 release @guangbochen https://github.com/harvester/harvester/pull/4435
  - [x] Bump dependencies
    - [x] rke2 is tagged to `v1.25.9+rke2r1` because the [regression bug](https://github.com/kubernetes/kubernetes/issues/118559) from newer k8s version `1.25.10 | 1.26.5 | 1.27.2`.
    - [x] bump Kubevirt patched version (to fix os-package CVEs) https://github.com/harvester/harvester/pull/4351
    - [x] validate whether bumping embedded Rancher to newer v2.7.6 release is required @guangbochen - Not required
  - [x] address v1.2.0 [required-for-rc issues](https://github.com/harvester/harvester/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.2.0+label%3Arequired-for-rc%2Fv1.2.0) @harvester/dev

- Release
  - [x] Cut Harvester Terraform v1.2.0-related release @futuretea [v0.6.3](https://github.com/harvester/terraform-provider-harvester/releases/tag/v0.6.3)
     - [x] Verify Rancher-v2 Terraform related version [compatibility-matrix](https://github.com/rancher/terraform-provider-rancher2/blob/master/docs/compatibility-matrix.md)
  - [x] Release Harvester v1.2.0 artifacts @guangbochen 
     - [x] Install mode artifact https://github.com/harvester/harvester/issues/4211
         - https://releases.rancher.com/harvester/v1.2.0/harvester-v1.2.0-amd64.raw.zst
  - [x] Release note @guangbochen & @bk201 
     - [x] Known issues & workaround
     - [x] Upgrade note 
     - [x] https://github.com/harvester/release-notes/pull/23 @LucasSaintarbor 

- Post Release
  - [x] Update v1.2.0 support matrix @rebeccazzzz 
  - [x] Set `v1.2.0` as the default doc version @guangbochen 
  - [ ] Update the harvester v1.2.0 upgrade-responder @bk201 & @guangbochen (1-2 days after v1.2.0 official release)
  - [x] v1.2.0 release article @yasker

**Comment by xeruf** [comment]
Is v1.2. safe to be released Thursday as the milestone says?
We would like to setup a Harvester instance this week and are wondering whether we should wait.

**Comment by guangbochen** [comment]
It is now available at https://github.com/harvester/harvester/releases/tag/v1.2.0; thank you all for your support and patience!

**Comment by ariker** [comment]
Will the upgrade-responder be updated soon?

**Comment by guangbochen** [comment]
Hi @ariker, thanks for your patience, we are preparing the Harvester v1.2.1 due to some known issues(mainly https://github.com/harvester/harvester/issues/4519); if you are interested and willing to upgrade to the v1.2.0 early, you may follow the [airgap upgrade method](https://docs.harvesterhci.io/v1.2/upgrade/index#prepare-an-air-gapped-upgrade), thanks. cc @bk201 @markhillgit

**Comment by ariker** [comment]
Thanks for the additional information
