### ISSUE TITLE
Add unit tests and integration tests

### ISSUE THREAD

**Issue by thxCode** [harvester/harvester#45]
**Improvement:**

It's necessary to add testings to control the quality of Harvester.

**Reference:**

- Construct the unit test cases based on the fake generated clientset. (TDD style)
- Construct the integration test cases based on the Ginkgo. (BDD style)

**TODO:**

- [x] Adjust the test script of dapper to support two kinds of test.
- [x] Add unit test cases.
- [x] Add integration test cases.
