### ISSUE TITLE
[EPIC] v1.2.1 upgrade related enhancements

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4553]
**Is your enhancement related to a problem? Please describe.**

Summarize all v1.2.1 upgrade related enhancements.

**Describe the solution you'd like**

**(1) Upgrade stuck in `Upgrading System Service`**
Issue:
[4519 [BUG] Upgrade to Harvester 1.2.0 fails in fleet-agent due to customer provided SSL certificate without IP SAN](https://github.com/harvester/harvester/issues/4519)
[4517 [BUG] Upgrade from 1.1.2 to 1.2.0 stuck 50% through the "Upgrading System Service"](https://github.com/harvester/harvester/issues/4517)

Fix:
- [x] fix fleet-agent;  rollback server-url sync in mcm settings handler https://github.com/harvester/harvester/pull/4543
- [ ] fix fleet-controller;  msg="error syncing 'fleet-local/local': handler import-cluster: missing apiServerURL in fleet config for cluster auto registration, requeuing"
- [ ] check self-signed certs; https://github.com/harvester/upgrade-helpers/pull/10

**(2)  Upgrade stuck with first node in Post-draining state**

Issue:
[4526 [BUG] Upgrade stuck with first node in Post-draining state](https://github.com/harvester/harvester/issues/4526)
https://github.com/rancher/elemental-toolkit/issues/1827

Fix:

- [x] (Harvester workaround) [upgrade: cleanup the incomplete state file](https://github.com/harvester/harvester/pull/4566)
#4566
- [x] (Elemental-toolkit) https://github.com/rancher/elemental-toolkit/pull/1836

**(3) Upgrade request denied - rancher-monitoring is not ready**

Issue: 
[4537 [BUG] Harvester 1.1.2 to 1.2.0 upgrade request denied - rancher-monitoring is not ready](https://github.com/harvester/harvester/issues/4537)
A derived issue https://github.com/harvester/harvester/issues/4581 is added.

Workaround:
In v1.1.2, the lost `cluster-repo` deployment was re-added.
In v1.2.0, the failed deployed `rancher-monitoring` addon was recovered manually.

Fix:  
- [ ] deployment `harvester-cluster-repo` was gone, re-created manualy;  reason unknown
- [ ] doc enhancement: when `rancher-monitoring` addon is not deployed during v120 upgrade, how to manually fix it after the upgrade

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
@w13915984028 are we good to close this epic? since all children issues are done

**Comment by w13915984028** [comment]
Finished.
