### ISSUE TITLE
[EPIC] Kubernetes-native Elemental CloudInit objects

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#4712]
Stories:

- [x] https://github.com/harvester/harvester/issues/4709
- [x] https://github.com/harvester/harvester/issues/3902
- [x] https://github.com/harvester/harvester/issues/4710
- [x] https://github.com/harvester/harvester/issues/4708

**Comment by irishgordo** [comment]
@connorkuehl 

Based around prior validation and additionally that:
- https://github.com/harvester/harvester/issues/5240

Will be in 1.4.0 milestone.

And that manual test docs have been merged in:
- https://github.com/harvester/tests/pull/1100

And that:
- https://github.com/harvester/harvester/issues/5110
has been created to track.

I'll go ahead and close this out :smile: :+1: 

Thanks for the awesome feature and docs!
