### ISSUE TITLE
[EPIC] Upgrade enhancement

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4926]
**Is your enhancement related to a problem? Please describe.**

Various upgrade enhancements.

**Describe the solution you'd like**

- Upgrade options. Some of the upgrade-relevant behaviors should be customizable by the users. Either expose them as fields under the Upgrade CRD or Harvester Settings.
   - [ ] Custom upgrade image (useful for development). (new field in the Upgrade CR) (https://github.com/harvester/harvester/issues/6183)
   - [x] Loading images in parallel. (#3059) (refer to a dedicated Harvester Setting)
   - [x] Skip image preloading. (#6028) (refer to a dedicated Harvester Setting)
   - [ ] Shutdown VMs. (new field in the Upgrade CR)
   - [x] Image clean-up. Unused images should be purge to release space. (https://github.com/harvester/harvester/issues/4425) (this is done automatically so there's no new option for it)
- Add more checks (some continue from https://github.com/harvester/harvester/issues/3067)
  - [ ]  timesync status on all nodes (timedatectl)
  - [ ] conflicting customizations in /oem/* (i.e. registries.yaml)
  - [ ] sufficient memory and CPU in the nodes
     - especially in case we add additional workload like monitoring/logging
     - For live-migration cases, we need to check if the rest nodes can absorb VMs from a upgrading node.
- Misc
  - [ ] Eliminate the upgrade-repo VM. (#7101)
  - [x] General version comparison tool/library (#2877)
  - [ ] Stand-alone Upgrade Manager (#7112)

**Comment by innobead** [comment]
This will be a continuous effort over releases. Adding to 1.7.0 first, as we are working on it. cc @starbops @Vicente-Cheng

**Comment by innobead** [comment]
Moved this EPIC to 1.8.0, as some unfinished items will be continued in the next release. 

cc @harvester/release

**Comment by innobead** [comment]
Moved this EPIC out of a specific milestone because its tasks will span multiple milestones. 

@starbops, please see what items we would like to achieve in 1.8.0 and add `candidate/v1.8.0` first to them. cc @Vicente-Cheng

**Comment by innobead** [comment]
Moved to the `active epics` milestone, as this EPIC needs efforts across milestones. 

cc @harvester/tpm
