### ISSUE TITLE
[ENHANCEMENT] Simplify Harvester dependencies

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5278]
**Is your enhancement related to a problem? Please describe.**

Some of our dependencies move fast and sometimes a change in the dependencies breaks features in Harvester and it takes too much effort to fix things from upstream or add workarounds [1][2].

We use embedded Rancher to control node management. It works with CAPI (Cluster-API). However, we don't have a good reason to use CAPI to control the cluster where it's deployed on. Also, rancher-provisioning-capi hard code `replicas` as 1 for capi-manager deployment [3]. If users remove a node and CAPI is on it, the cluster will be unstable.

We can review embedded dependencies and see if we can implement the functions those dependencies provide.

Features rely on Rancher:
- rancher-expose ingress: rancher server is entry point for harvester UI.
- auth server: admin login/logout function.
- promote-node-controller: adding labels on node to promote a node from agent to server.
- rancher-system-agent: `containerd-registry` and `auto-rotate-rke2-certs` settings need rancher-system-agent to execute machine plan.
- SUC (system-upgrade-controller) plans: `additional-ca` setting use SUC plans to add CA on each node.
- Fleet: ManagedChart use bundles CRD in Fleet and our system uses ManagedChart to install Harvester.

**Describe the solution you'd like**

- Implement dependencies functions within Harvester controllers. Or,
- Fork dependencies, strip unnecessary codes, and maintain our repos.

The change should allow upgrading from previous versions without issues.

**Describe alternatives you've considered**

**Additional context**

[1] Bumping Rancher from 2.7.5 to 2.7.9, Rancher change CAPI from embedded controller to independent deployment. https://github.com/harvester/harvester-installer/pull/605
[2] Fleet 0.9.0 and 0.9.2 use different `nullable` values on field `correctDrift`. Bumping Rancher from 2.8.2 to 2.8.3, UI always show ManagedChart is in progress, even if it's done. https://github.com/harvester/harvester/issues/5923
[3] https://github.com/rancher/charts/blob/c741034bb85bb49454a2fe1c043fb12223c0f696/charts/rancher-provisioning-capi/104.0.0%2Bup0.2.0/templates/deployment-capi-controller-manager.yaml#L10

**Comment by FrankYang0529** [comment]
#### Replace rancher-expose with harvester-expose

If we do following change to an existent harvester cluster. We can access harvester dashboard directly without rancher.

* Remove `rancher-expose` ingress.
* Change `HARVESTER_SERVER_HTTP_PORT` from `0` to `8080` in harvester deployment.
* Add http port to harvester deployment.
```yaml
        - containerPort: 8080
          name: http
          protocol: TCP
```
* Add http port to harvester service.
```yaml
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
```
* Create `harvester-expose` ingress.
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harvester-expose
  namespace: harvester-system
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: harvester
            port:
              number: 8080
        path: /
        pathType: Prefix
```

https://github.com/harvester/harvester/assets/4927361/6a0903fc-2455-4672-be73-e182936cc23d

#### Migrate rancher auth server to harvester

The reason we can access Harvester dashboard directly is that we use `steveauth.AlwaysAdmin`.
https://github.com/harvester/harvester/blob/13b8f77204c2a28361d87ed26e7d63b1555f7662/pkg/server/types.go#L251

With PR https://github.com/harvester/harvester/pull/5869, I tried to migrate rancher auth server to harvester. We can try to replace harvester deployment image with `frankyang/harvester:HARV-5278-head`. However, the result is not good. I got following errors:
```
panic: feature gate "AdvancedAuditing" with different spec already exists: {true true }

goroutine 1 [running]:
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime.Must(...)
    /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:175
github.com/harvester/harvester/vendor/k8s.io/kubernetes/pkg/features.init.0()
    /go/src/github.com/harvester/harvester/vendor/k8s.io/kubernetes/pkg/features/kube_features.go:914 +0x3f
```

**Comment by FrankYang0529** [comment]
After digging into Rancher source code, if we still rely on rancherd to setup new nodes, it will be hard to deprecate embedded rancher. The reason is whole path relies on Cluster API (CAPI) to setup a cluster.

For the first node, it sets up rancherd -> RKE2 -> Rancher -> Fleet -> Using management chart to install Harvester. If we set `embedded-cluster-api=false`, the process is stuck in setup Rancher step, because the cluster can't find CAPI CRDs. However, if we use embedded CAPI in Rancher, [the replica number is constant as 1](https://github.com/rancher/charts/blob/2288f8ae3032be78307d44ece275ea5c18f50a91/charts/rancher-provisioning-capi/104.0.0%2Bup0.2.0/templates/deployment-capi-controller-manager.yaml#L10) which doesn't give a good availability. For example, if users want to remove a machine which is host for capi-controller-manager pod, then the cluster will be unsteady.

If we want to deprecate embedded Rancher but keeping some features from it like certificate rotation / setting up registry, we need to find a way to enhance availability of capi-controller-manager. One way is to make it as an variable for replicas field in the upstream. Another way is to install our own CAPI, but we can't do it in harvester dependencies charts, because it's final step in setting up a node.

If we can abandon features from Rancher, we can remove the whole CAPI related components (rancherd and Rancher). For examples, we can install cluster like https://docs.rke2.io/install/quickstart#server-node-installation. For certificate rotation, we can run commands on each server like https://docs.rke2.io/security/certificates?_highlight=certi#rotating-client-and-server-certificates-manually. To run command on each server, we can install [system-upgrade-controller](https://github.com/rancher/system-upgrade-controller) without Rancher.

**Comment by w13915984028** [comment]
Could we add a HEP to track this enhancement?

The Rancher&RKE2&K3s are a big group of k8s encapsulation&enhancement feature sets, we need a deep investigation and consolidate the boundaries of them, then with a plan to replace step by step.

**Comment by FrankYang0529** [comment]
## Original setup and config
### Setup flow
* First node: rancherd -> RKE2 server -> Rancher -> Fleet -> Installing Harvester by ManagedChart
* Other nodes: rancherd -> rancher-system-agent -> RKE2 agent
* Promotion node: promote-node-controller adds labels -> Rancher generates new machine plan -> rancher-system-agent execute plan (disable RKE2 agent and enable RKE2 server)

### rancherd config
* First node:
```yaml
role: cluster-init
# other fields
```
* Other nodes:
```yaml
server: https://<vip>:443
role: agent
# other fields
```

## New setup and config
### Setup flow:
* First node: rancherd -> RKE2 server -> Rancher (only enable `auth` feature)-> Installing Harvester by HelmChart
* Other nodes: rancherd -> RKE2 server/agent (Users can choose to deploy server by giving `Role` as `management` or `witness` in Harvester config)

### rancherd config:
* First node:
```yaml
role: cluster-init
# other fields
```
* Other server nodes (`management` and `witness` roles):
```yaml
server: https://<vip>:443
role: server
# other fields
```
* Other agent nodes (`default` and `agent` roles):
```yaml
server: https://<vip>:443
role: agent
# other fields
```

### Build New ISO

1. Build rancherd (https://github.com/rancher/rancherd/tree/simplify-harv-dependencies)
```sh
git clone https://github.com/rancher/rancherd.git -b simplify-harv-dependencies
cd rancherd
make
```
2. Build images
```sh
git clone https://github.com/harvester/harvester.git -b simplify-harv-dependencies
cd harvester
REPO=<docker hub name> make
docker push <docker hub name>/harvester:<tag>
docker push <docker hub name>/harvester-webhook:<tag>
docker push <docker hub name>/harvester-upgrade:<tag>
```
3. Start a file server to provide rancherd artifacts.
```sh
cd <rancherd folder>
cd dist/artifacts
python -m http.server
```
4. Update rancherd endpoint in harvester-installer.
https://github.com/harvester/harvester-installer/blob/8f916ff8e1af8efe616a6d3632c954a76bfa9c11/package/harvester-os/Dockerfile#L14
5. If you update both harvester and harvester-installer, update `build-iso` script first.
https://github.com/harvester/harvester/blob/ce674e5bd220cef80c917d6428040920b531646f/scripts/build-iso#L10-L12
6. Build ISO
```sh
cd <harvester folder>
REPO=<docker hub name> make build-iso
```

### Start a cluster with new ISO

Change `role` from `default` to `management` for the second and third nodes.

* https://github.com/harvester/ipxe-examples/blob/b04d4434577f934f7218f0e110b17fd727df2207/vagrant-pxe-harvester/settings.yml#L84
* https://github.com/harvester/ipxe-examples/blob/b04d4434577f934f7218f0e110b17fd727df2207/vagrant-pxe-harvester/settings.yml#L92


### TODO

* [X] Add system-upgrade-controller to harvester-cluster-repo. (In harvester-installer commit: "feat: add system-upgrade-controller to bundle")
* [X] Add fleet & fleet-crd to harvester-cluster-repo. (In harvester-installer commit: "feat: add fleet & fleet-crd to bundle")
* [X] Replace ManagedChart with Bundle. (In harvester-installer commit: "feat: change ManagedChart to HelmChart" and "feat: change HelmChart to Bundle")
* [X] Add Bundle webhook. We had some webhook to prevent users from deleting some ManagedChart. We also need it for Bundle. (In harvester-installer commit: "feat: change HelmChart to Bundle")
* [X] Use SUC plan to handle `containerd-registry` setting. (In harvester commit: "feat: use SUC plan for containerd-registry")
* [X] Use SUC plan to handle `auto-rotate-rke2-certs` setting. (In harvester commit: "feat: use SUC plan for auto-rotate-rke2-certs")
* [X] Use SUC plan to handle `http-proxy` setting. (In harvester commit: "feat: add sync-plan-to-server and sync-plan-to-agent")
* [X] Handle `auto-disk-provision-paths` setting in Bundle. (In harvester commit: "feat: remove ManagedChart & App & Rancher Setting controller")
* [X] Handle `support-bundle-image` setting. If default `support-bundle-image` is empty, we tried to get default value from ManagedChart. Change to get it from helm values. (In commit: "feat: get image from helm values")
* [X] Handle `schedule-vm-backup-controller` and `cpu-manager-controller` to get general job image from helm values. (In commit: "feat: get image from helm values")
* [X] Handle `storage-network` setting. We used `checkRancherMonitoringStatusAndStart` and `checkRancherMonitoringStatusAndStop` to pause ManagedChart and restart rancher-monitoring. Change to use Bundle. (In harvester commit: "feat: remove ManagedChart & App & Rancher Setting controller")
* [X] Move `ingress-expose` creation from rancher package to `data.Init`. (In harvester commit: "feat: create ingress-expose service")
* [ ] Move auth server to Harvester. https://github.com/harvester/harvester/issues/6997
* [ ] Add promote-node-controller back (Need to discuss).
* [X] Handle upgradelog controller. We checked `rancher-logging` ManagedChart and set it to UpgradeLog condition. (In harvester commit: "feat(upgrade): change to use bundle to install rancher-logging")
* [X] Handle upgradelog controller. It creates logging-operator ManagedChart. We should replace it with Bundle. (In harvester commit: "feat(upgrade): change to use bundle to install rancher-logging")
* [X] Handle upgrade webhook. We checked ManagedChart status. (In harvester commit: "feat: remove ManagedChart & App & Rancher Setting controller")
* [ ] Update content in harvester-release.yaml.
* [ ] Upgrade path. We may need another issue to track this cause this is a big change. We have to disable old controllers to safely delete old CRDs (CAPI / Fleet / Rancher) and use new CRD to control the cluster.
* [ ] Handle `cattle-fleet-system/fleet-controller` ConfigMap. In `watch-fleet-controller-cm`, we change `apiServerURL` and `apiServerCA` to rancher setting. We may need to revert this during upgrade.
* [ ] Handle `ssl-certificate`. It tries to redeploy rancher deployment. We may need to change to harvester-auth.
* [ ] Harvester UI. https://github.com/harvester/harvester/issues/6998
* [ ] Run rancher-system-agent without embedded rancher. https://github.com/harvester/harvester/issues/7039

**Comment by bk201** [comment]
Some deployment has the `management.cattle.io/scale-available` annotation. Rancher manages the deployment dynamically according to the annotation's value.

**Comment by wheatdog** [comment]
@Vicente-Cheng @innobead @bk201 I'm interested in this topic and self-assigned. As the first step, I would read the previous analysis from @FrankYang0529 and check the current status.

**Comment by innobead** [comment]
This is a duplicate of https://github.com/harvester/harvester/issues/10712. Let's use 10712 to track the development instead. 

cc @bk201 @wheatdog
