### ISSUE TITLE
[FEATURE] VM Snapshot support

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#553]
The user should be able to create an in-cluster snapshot and revert back to it later.

This in addition to #479 , which only covers backup to the outside of the cluster.

**Comment by guangbochen** [comment]
@yasker since the LH snapshot does not have a CRD and can only be maintained through API calls, do u have any other recommendations, thanks.

**Comment by yasker** [comment]
Snapshot CRD is a scheduled feature in https://github.com/longhorn/longhorn/issues/2534

**Comment by yasker** [comment]
Due to the dependency of CSI snapshot for Longhorn snapshot (instead of backup), move the feature to v1.1.0 instead.

**Comment by weihanglo** [comment]
Note that we might not get a native support of VM snapshot revert because its out of scope of CSI snapshotter at this moment. Though we can try to reuse the same trick in backup by replacing the VM with a new volume.

Ref: https://github.com/longhorn/longhorn/blob/119677db04b5a0fdcfab19a6211370a03d784164/enhancements/20220110-extend-csi-snapshot-to-support-longhorn-snapshot.md#non-goals

**Comment by yasker** [comment]
cc @PhanLe1010

**Comment by PhanLe1010** [comment]
Support for CSI snapshot to Longhorn snapshot is coming in Longhorn 1.3.0 https://github.com/longhorn/longhorn/issues/2534

**Comment by FrankYang0529** [comment]
This issue will focus on this case:
* VM Snapshot on VM page.
![Screen Shot 2022-05-20 at 1 33 03 PM](https://user-images.githubusercontent.com/4927361/169458045-a862897f-fadd-4642-8608-d01e3105b748.png)

### TODO:
* [X] Upgrade LH to v1.3.0. (https://github.com/harvester/harvester/pull/2695)
* [X] Based on [LH CSI Snapshot](https://github.com/longhorn/longhorn/issues/2534#issuecomment-1010508714), add a new `VolumeSnapshotClass` with parameter `type: snap`. https://github.com/harvester/harvester/pull/2355
* [X] VM snapshot https://github.com/harvester/harvester/pull/2355
  * [ ] ~Add a new [action](https://github.com/harvester/harvester/blob/d84626073138f38e1d4624e835c59c6ea282e61b/pkg/api/vm/handler.go#L80-L174) to VM handler.~ (We can just create a snapshot by applying a VMBackup object, so we don't need to add a new handler.)
  * [X] Add a field `type` to [VirtualMachineBackupSpec](https://github.com/harvester/harvester/blob/d84626073138f38e1d4624e835c59c6ea282e61b/pkg/apis/harvesterhci.io/v1beta1/backup.go#L53-L55). Valid values will be `backup` and `snapshot`. Using `backup` as a default value for old version compatibility.
  * [X] Update [backup controller](https://github.com/harvester/harvester/blob/d84626073138f38e1d4624e835c59c6ea282e61b/pkg/controller/master/backup/backup.go#L112).

**Comment by futuretea** [comment]
@FrankYang0529 create a new issue for  add volume action snapshot: https://github.com/harvester/harvester/issues/2294

**Comment by futuretea** [comment]
@FrankYang0529  A vm may have may volumes. If different volume has different driver, add  `VolumeSnapshotClassName` in `VirtualMachineBackupSpec`  seems impossible to handle the situation.

the design `Add a field type to VirtualMachineBackupSpec`  seems more flexibility，we can read from VolumeSnapshotClassName from settings.

If we want to support different driver, we can extend the VolumeSnapshotClassName settings  later (https://github.com/harvester/harvester/issues/2295）

**Comment by FrankYang0529** [comment]
@futuretea, do you mean there is a case that users may have a VM with many volumes and each volume is from different drivers? If this is the case, I can update VM snapshot PR and follow the setting in #2295 :

```
{
  "driver.longhorn.io": {
    "volumeSnapshotClassName": "longhorn-snapshot",
    "backupVolumeSnapshotClassName": "longhorn",
    "supportClone": true,
    "supportExpand": true,
    "supportExport": true
  },
  "csi-vxflexos.dellemc.com": {
    "volumeSnapshotClassName": "vxflexos-snapclass",
    "backupVolumeSnapshotClassName": "",
    "supportClone": true,
    "supportExpand": true,
    "supportExport": false
  }
}
```

**Comment by lanfon72** [comment]
Verified this feature has been implemented.


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **master-3bcba9d3-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Create an Image for VM creation
3. Create `vm1` with the image and an additional data volume `disk-1`
4. Login to `vm1`, execute following commands:
    - `fdisk /dev/vdb` with new and primary partition
    - `mkfs.ext4 /dev/vdb1`
    - `mkdir vdb && mount -t ext4 /dev/vdb1 vdb`
    - `ping 127.0.0.1 | tee -a test vdb/test`
5. Navigate to _Virtual Machines_ page, click **Take Snapshot** button on `vm1`'s details, named `vm1s1`
6. Execute `sync` on `vm1` and **Take Snapshot** named `vm1s2`
7. Interrupt `ping...` command and `rm test && sync`, then **Take Snapshot** named `vm1s3`
8. Restore 3 snapshots into **New** VM: `vm1s1r`, `vm1s2r` and `vm1s3r`
9. Content of `test` and `vdb/test` should be the same  in VM, and different in other restored VMs.
10. Restore snapshots with **Replace Existing**
11. Content of `test` and `vdb/test` in restored `vm1` from the snapshot, should be the same as the VM restored with the same snapshot.
