### ISSUE TITLE
[FEATURE] VM Clone support without backupstore

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#569]
We should be able to support clone VM along with all of the data.

~~Depends on: https://github.com/longhorn/longhorn/issues/1815~~

After investigation, it depends on https://github.com/longhorn/longhorn/issues/2534 .

**Comment by yasker** [comment]
Due to the dependency on https://github.com/longhorn/longhorn/issues/2534 , move the feature to v1.1.0.

**Comment by FrankYang0529** [comment]
For this feature, I think we can leverage the current design in VM. We use the annotation `harvesterhci.io/volumeClaimTemplates` to create PVC in the harvester controller. We can add a `dataSource` field to it, so users can get a new VM with cloned PVC from the target VM.

So we may need two PR to achieve this:
* A UI PR to add a `clone` button on VM. When users click it, UI will go to the `Virtual Machine: Create` page for users to modify the VM name or other settings. Also, in VM YAML, UI needs to add `dataSource` to each PVC in the `harvesterhci.io/volumeClaimTemplates` annotation.
* A webhook PR to check whether the `dataSource` is valid (`kind` must be `PersistentVolumeClaim` and source PVC is existent ).

cc @guangbochen @weihanglo

**Comment by FrankYang0529** [comment]
I've tested that adding `dataSource` to `harvesterhci.io/volumeClaimTemplates` can work.

Steps:
* Create a VM.
* Login to the VM and add a file `test.txt` with content `123`.
* Create another VM, but don't click the `Create` button directly. Click `Edit as YAML`.
* Add `"dataSource":{"name":"vm-disk-0-xxx","kind":"PersistentVolumeClaim"}` to `harvesterhci.io/volumeClaimTemplates` annotation. The name of PVC is from first VM.
* Click the `Create` button.
* Login to the new VM and check whether the file is existent and the content is the same.

**Comment by weihanglo** [comment]
The proposal looks great! Leveraging CSI volume-cloning is really reasonable. I wonder why @yasker thought it should depend on CSI snapshot but volume cloning.

**Comment by yasker** [comment]
I vaguely remembered some discussion around the area. But @PhanLe1010 is the expert on this part and he should know better.

**Comment by weihanglo** [comment]
FWIW, there are a proposal and an implementation of VM cloning support in KubeVirt:

- https://github.com/kubevirt/community/pull/159
- https://github.com/kubevirt/kubevirt/pull/7336


Though there are some unneglectable limitations described in that proposal:

- Only offline cloning will be supported, meaning cloning a VM when it's stopped.
- Cloned VM would be in the same namespace as the original one.
- Host disks would not be supported.

**Comment by FrankYang0529** [comment]
> * Only offline cloning will be supported, meaning cloning a VM when it's stopped.

From my experiment, I think our design can clone a live VM. However, not sure whether it impacts the source PVC if we keep writing data to it during cloning a VM. This relies on LH.

> * Cloned VM would be in the same namespace as the original one.

`PVC.spec.dataSource` is a `TypedLocalObjectReference` object. From k8s source code, we also can only clone a VM in the same namespace.

https://github.com/kubernetes/kubernetes/blob/8aaea8e24c1b87dbd606801f3c3f1e51ee4da44e/staging/src/k8s.io/api/core/v1/types.go#L5687-L5700

> * Host disks would not be supported.

Not sure about this one.

**Comment by FrankYang0529** [comment]
> ... I wonder why @yasker thought it should depend on CSI snapshot but volume cloning.

> I vaguely remembered some discussion around the area. But @PhanLe1010 is the expert on this part and he should know better.

Hi @PhanLe1010, could you please help to respond to these two comments☝🏻? Thank you.

**Comment by PhanLe1010** [comment]
I just reviewed the design discussion in the past: https://confluence.suse.com/display/LON/High-level+LEP+for+Longhorn+volume+cloning+and+Harvester+VM+cloning

In a nut shell, there are 3 ways for Harvester to do clone:
* [CDI smart-cloning feature](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/smart-clone.md)
* CSI volume clone, mentioned by @FrankYang0529 at [link](https://github.com/harvester/harvester/issues/569#issuecomment-1123096360)
* CSI volume snapshot, [link](https://github.com/longhorn/longhorn/issues/2534). See more details about this option in the comment section

In the past, we didn't pick the CDI ways because Harvester don't want to depend on CDI

For the decision between `CSI volume clone` and `CSI volume snapshot`. The downside of using `CSI volume clone` right now is Longhorn creates a new Longhorn snapshot for the source volume after a clone. This snapshot is not cleaned up automatically after the cloning and requires manual operation. This should be improved by future Longhorn releases. `CSI volume cloning` is also needing some polishments as described in the ticket: https://github.com/longhorn/longhorn/issues/2907

If Harvester uses `CSI volume snapshot` way by:
```
We can introduce a VMClone CRD to manage the snapshot creation. (Probably repeat/similar to the CDI controller logic in CDI smart-cloning)
1. It creates CSI snapshots from the VM volumes.
2. It creates the cloned VM with PVCs using snapshots as the dataSource
3. Delete the  CSI snapshots in the step 1
4. If any error in the process repeated the steps 1->3
```
Harvester can have more control over the process and avoid the corner cases that the `CSI volume cloning` is facing.

**Comment by FrankYang0529** [comment]
This feature has two use cases:
* Cloning a VM on Harvester UI.
![Screen Shot 2022-05-19 at 5 10 48 PM](https://user-images.githubusercontent.com/4927361/169257746-cca86ef9-4c89-40d6-81bb-c3979984f335.png)
* Create a RKE node by cloning a VM like what we can do on vSphere.
![Screen Shot 2022-05-19 at 5 07 24 PM](https://user-images.githubusercontent.com/4927361/169257020-022534be-7c45-4e08-b287-06411219793e.png)
 
For the second use case, we can create a CR from a source node and use it to create new RKE nodes. This CR may be template/snapshot/clone. If we would like to introduce a new CRD `VMClone` here, I think it may be redundant. We already have other two issues focus on similar thing. #553 #571 

We need to review these three issues and choose one to implment _VM template with data state_ feature. For this issue, I prefer to focus on cloning VM on harvester UI, so the easiest way would be volume cloning in https://github.com/harvester/harvester/issues/569#issuecomment-1123096360.

cc @bk201 @guangbochen @weihanglo

**Comment by FrankYang0529** [comment]
This issue will focus on cloning volume on the Harvester dashboard. Users can only change a name of a new VM when they click `Clone` button. If they would like to modify other fields, they can edit VM after a new VM is created. If they would like to edit VM in advance, they can use the template feature in https://github.com/harvester/harvester/issues/571.

~We would like to let backup handle the cloning process, but we don't want to introduce a new CRD, so we will add a hook label to `VMBackup` CRD to create a new VM.~

**(Update on 05/27)** After discussing with @futuretea and @guangbochen, we feel that introducing `hooks` in VMBackup may let logic complicated. Also, after users click the `clone` button, it is hard to show a VM on UI first, because we need to wait for VMBackup complete. Users are hard to track the `clone` behavior if there is an error in the process.
We still follow the design in https://github.com/harvester/harvester/issues/569#issuecomment-1123096360, but we add `dataSource` to `harvesterhci.io/volumeClaimTemplates` in the API handler, so we don't need to put too much logic in UI.

### TODO
* [ ] ~Add a new label `harvesterhci.io/hooks` to `VMBackup` CRD. The value of the label is a JSON string and its structure is like the following.~
```
{
  "actions": [
    {
      "action": "retore-vm",
      "params": {
        "name": "new-vm",
      }
    }
  ]
}
```
* [ ] ~Handle hook label in [backup](https://github.com/harvester/harvester/blob/d84626073138f38e1d4624e835c59c6ea282e61b/pkg/controller/master/backup/backup.go#L112) controller.~
* [x] Add a `cloneVM` API and add `dataSource` of `harvesterhci.io/volumeClaimTemplates` in API handler. https://github.com/harvester/harvester/pull/2338
* [x] Update `clone` behavior on UI. https://github.com/harvester/dashboard/pull/357

**Comment by noahgildersleeve** [comment]
Tested in master-1b8226cf-head with steps [here](https://github.com/harvester/tests/issues/361).

> ### Case 1
> 1. Create a harvester cluster.
> 2. Create a VM `source-vm` with 3 volumes:
> 
> * Image Volume
> * Volume
> * Container Volume
> 
> 3. After VM starts, run command `echo "123" > test.txt && sync`.
> 4. Click `clone` button on the `source-vm` and input new VM name `target-vm`.
> 5. A new VM `target-vm` is created and running.
> 6. Check `target-vm` YAML. There should have `dataSource` field in `harvesterhci.io/volumeClaimTemplates` annotation. Also format of PVC name should be `<vm-name>-<volume-name>-<random-string>` and format of secret reference should be `<vm-name>-<random-string>`.
>    ![Screen Shot 2022-06-02 at 11 45 40 AM](https://user-images.githubusercontent.com/4927361/171548898-6cbf59e2-9fd2-4dbb-ba3e-e95de62907c6.png)
>    ![Screen Shot 2022-06-02 at 11 46 45 AM](https://user-images.githubusercontent.com/4927361/171549014-52753794-fc76-416f-a75b-9aabd928ebff.png)
> 7. Run command `cat ~/test.txt` in the `target-vm`. The result should be `123`.
> 
> ### Case 2
> 1. Follow case 1, click `Clone` on `target-vm` to create a new VM `new-target-vm`.
> 2. The `new-target-vm` also contains `~/test.txt` and its content is `123`.
> 
> ### Case 3
> 1. Follow case 2, click `Clone template` on `new-target-vm` to create a new VM `clone-template-vm`.
> 2. The new `clone-template-vm` has same storage size as `new-target-vm`, but its storage is clean and doesn't contain `~/test.txt` file.

**Comment by noahgildersleeve** [comment]
Updated negative tests and am creating PR for updated clone vm test logic
