### ISSUE TITLE
[FEATURE] Backend support USB Host Passthrough

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#5762]
**Is your feature request related to a problem? Please describe.**

Regarding #1710, we need to implement USB Host Passthrough on the node. This ticket is for backend.

**Describe the solution you'd like**

According to HEP https://github.com/harvester/harvester/issues/5430 to implement solution.

**Related Issue**
https://github.com/harvester/harvester/issues/1710

**Todo**

Core Business Logic
- [x] https://github.com/harvester/harvester/issues/5746
- [x] Create `usbdevice` and `usbdeviceclaim` CRD
- [x] Build custom device plugin to replace kubevirt device plugin logic
- [x] Detect all USB devices in the period of time, including detailed usb device information
- [x] Claim USB device to update `kubevirt` CR
- [x] Restart device plugin grpc server when restarting server 
- [x] Verify if Daemonset have the USB permission
- [x] Backup USB vendor/product database locally
- [x] Add unit test

Webhook
- [x] Block request that delete bound/used claimed usb device 
- [x] Block request that delete bound/used usb device
- [x] Block request that assign usb device to vm, but the node affiliates between usb device and vm don't match
- [x] Block request that in-used usbdevice's pci device is not allowed to pass through
- [x] Add unit test

Charts Permission Related
- [x] Daemonset should have /dev/bus mounted https://github.com/harvester/charts/pull/246

Docs
- [x] List some limitations to warn users
- [x] harvester/pcidevices README

Current found issues after self testing
- https://github.com/harvester/pcidevices/pull/86

**Comment by kamushadenes** [comment]
Are all tasks really complete? If so, when can this feature be expected to release?

**Comment by Yu-Jack** [comment]
@kamushadenes It's still in reviewing phase.

**Comment by kamushadenes** [comment]
Thank you, Jack. 

Can I help in any way, maybe testing?

**Comment by Yu-Jack** [comment]
Since QA had closed parent issue and [left a comment](https://github.com/harvester/harvester/issues/1710#issuecomment-2418444324), so I close this one.
