### ISSUE TITLE
[Task] Harvester v0.2.0 release checklist

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#741]
**What's the task? Please describe.**
Action items for releasing v0.2.0

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] make sure the `harvester-network-controller` release is up-to-date @yaocw2020
- [x] make sure the `harvester-ui` release is up-to-date @WuJun2016
- [x] make sure the `harvester-node-driver` release is up-to-date @futuretea
- [x] make sure the `harvester-installer` release is up-to-date @gitlawr 
- [x] make sure the longhorn is using the latest `v1.1.1` release @guangbochen 
- [x] bump harvester document to reflect v0.2.0 changes @guangbochen  https://github.com/harvester/harvester/pull/732
- [x] add release note @guangbochen 
- [x] make sure the support bundle feature is added https://github.com/harvester/harvester/issues/579
- [x] make sure the repo reference is updated to use `harvester` https://github.com/harvester/harvester/issues/727
- [x] make sure update the rancher server to latest `2.5.x`

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/releases/tag/v0.2.0
